MultiStageSettingsDict:
  Myopic: 0
  ConvergenceTolerance: 0.01
  WACC: 0.045
  StageLengths:
    - 5
    - 5
    - 5
  CurStage: 3
  NumStages: 3
NetworkExpansion: 0
TimeDomainReductionFolder: "TDR_Results"
ParameterScale: 0
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
Reserves: 1
StorageLosses: 1
OperationWrapping: 1
MultiStage: 1
OverwriteResults: 0
UCommit: 2
ModelingToGenerateAlternatives: 0
MinCapReq: 0
CO2Cap: 2
WriteShadowPrices: 1
